// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// predprobCpp
double predprobCpp(int y, int n, int nmax, double alpha_e, double beta_e, double p_s, double theta_t);
RcppExport SEXP _ph2bayes_predprobCpp(SEXP ySEXP, SEXP nSEXP, SEXP nmaxSEXP, SEXP alpha_eSEXP, SEXP beta_eSEXP, SEXP p_sSEXP, SEXP theta_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nmax(nmaxSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_e(alpha_eSEXP);
    Rcpp::traits::input_parameter< double >::type beta_e(beta_eSEXP);
    Rcpp::traits::input_parameter< double >::type p_s(p_sSEXP);
    Rcpp::traits::input_parameter< double >::type theta_t(theta_tSEXP);
    rcpp_result_gen = Rcpp::wrap(predprobCpp(y, n, nmax, alpha_e, beta_e, p_s, theta_t));
    return rcpp_result_gen;
END_RCPP
}
