# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predprobCpp <- function(y, n, nmax, alpha_e, beta_e, p_s, theta_t) {
    .Call(`_ph2bayes_predprobCpp`, y, n, nmax, alpha_e, beta_e, p_s, theta_t)
}

